#---------------------------------------------------------------------------------
# abstarwars2_nx.nro: launcher (64-bit) for Angry Birds Star Wars II
#---------------------------------------------------------------------------------
APP_TITLE    := Angry Birds Star Wars II
APP_AUTHOR   := Rovio Entertainment
APP_VERSION  := 1.0.0
TARGET       := abstarwars2_nx
PORT_PAYLOAD := abstarwars2_nx
LAUNCHER_SOURCES :=
TOPDIR ?= $(CURDIR)
A32    ?= $(TOPDIR)/../runtime
include $(A32)/launcher/launcher.mk
